#
# LICENSE UPL 1.0
#
# Copyright (c) 2018, 2020 Oracle and/or its affiliates.
#
# Since: February, 2018
# Author: sergio.leunissen@oracle.com
# Description: Creates an Docker engine installation on Oracle Linux 7 using Btrfs
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

# 中文说明：
# - 该文件定义基于 Oracle Linux 7 的 Docker Engine 虚拟机。
# - 额外挂载持久磁盘用于 Docker 存储，并在首次启动时执行安装脚本。

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Required for the Disks feature
Vagrant.require_version ">= 2.2.8"
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
BOX_NAME = "oraclelinux/7"

# define hostname
NAME = "ol7-docker-engine"

# Convenience function -- Ensure URL has a scheme
def ensure_scheme(url)
  (url =~ /.*:\/\// ? '' : 'http://') + url
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.define NAME

  # Set proxies if vagrant-proxyconf is installed
  if Vagrant.has_plugin?("vagrant-proxyconf")
    # 中文：继承宿主机代理，方便拉取软件包和容器镜像。
    ["http_proxy", "HTTP_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        puts "HTTP 代理：" + proxy
        config.proxy.http = ensure_scheme(proxy)
        break
      end
    end

    ["https_proxy", "HTTPS_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        puts "HTTPS 代理：" + proxy
        config.proxy.https = ensure_scheme(proxy)
        break
      end
    end

    # We should not proxy local IPs (docker bridge, ...)
    # Unfortunately we can't use CIDR with no_proxy, so we have to enumerate and
    # 'blacklist' *all* IPs
    no_proxy = ''
    ["no_proxy", "NO_PROXY"].each do |proxy_var|
      if ENV[proxy_var]
        no_proxy = ENV[proxy_var]
        puts "不使用代理：" + no_proxy
        no_proxy += ','
        break
      end
    end
    config.proxy.no_proxy = no_proxy + "localhost,.vagrant.vm," + (".0"..".255").to_a.join(",")
  end

  # change memory size
  # 中文：同时为 Docker 数据区附加独立持久磁盘。
  config.vm.provider "virtualbox" do |v, override|
    v.memory = 2048
    v.name = NAME
    override.vm.disk :disk, size: '16GB', name: 'docker_storage'
  end
  config.vm.provider :libvirt do |v|
    v.memory = 2048
    v.storage :file, :size => '16G', :type => 'qcow2'
  end


  # VM hostname
  config.vm.hostname = NAME + ".vagrant.vm"

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh"

  end
