. /vagrant/config/setup.env
/u01/app/oracle/product/19.0.0/dbhome_1/bin/dbca -silent -createDatabase \
  -templateName General_Purpose.dbc \
  -initParams db_recovery_file_dest_size=2G \
  -responseFile NO_VALUE \
  -gdbname ORCL \
  -characterSet ZHS16GBK \
  -nationalCharacterSet AL16UTF16 \
  -sysPassword oracle \
  -systemPassword oracle \
  -createAsContainerDatabase true \
  -numberOfPDBs 1 \
  -pdbName PDB1 \
  -pdbAdminPassword oracle \
  -databaseType MULTIPURPOSE \
  -automaticMemoryManagement false \
  -totalMemory 2048 \
  -redoLogFileSize 50 \
  -emConfiguration NONE \
  -ignorePreReqs \
  -databaseConfigType RAC \
  -nodelist node1,node2 \
  -storageType ASM \
  -diskGroupName +DATA \
  -recoveryGroupName +RECO \
  -asmsnmpPassword oracle
