#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# 07_setup_OracleNet.sh
#   Writes tnsnames.ora / listener.ora / sqlnet.ora on both nodes and
#   starts the local listener. Runs as the oracle user.
#------------------------------------------------------------------------------
. /vagrant/scripts/_common.sh

if [[ "$(id -un)" != "oracle" ]]; then
  log_error "this script must run as the oracle user"
  exit 1
fi

require_var DB_HOME
require_var DB_BASE
require_var DB_NAME
require_var NODE1_HOSTNAME
require_var NODE2_HOSTNAME

net_admin="${DB_HOME}/network/admin"
mkdir -p "${net_admin}"

current_host="$(hostname -s)"
case "${current_host}" in
  "${NODE1_HOSTNAME}") local_node="${NODE1_HOSTNAME}"; global_dbname="${DB_NAME}_DGMGRL" ;;
  "${NODE2_HOSTNAME}") local_node="${NODE2_HOSTNAME}"; global_dbname="${DB_NAME}_STDBY_DGMGRL" ;;
  *)
    log_error "hostname '${current_host}' is neither primary nor standby"
    exit 1
    ;;
esac

log_section "Writing tnsnames.ora on ${current_host}"
cat > "${net_admin}/tnsnames.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER = (ADDRESS = (PROTOCOL = TCP)(HOST = ${local_node})(PORT = 1521))

${DB_NAME} =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE1_HOSTNAME})(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${DB_NAME})
    )
  )

${DB_NAME}_STDBY =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE2_HOSTNAME})(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${DB_NAME})
    )
  )
EOF

log_section "Writing listener.ora on ${current_host}"
cat > "${net_admin}/listener.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${local_node})(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = ${global_dbname})
      (ORACLE_HOME   = ${DB_HOME})
      (SID_NAME      = ${DB_NAME})
    )
  )

ADR_BASE_LISTENER = ${DB_BASE}
INBOUND_CONNECT_TIMEOUT_LISTENER = 400
EOF

log_section "Writing sqlnet.ora"
cat > "${net_admin}/sqlnet.ora" <<'EOF'
# Generated by Vagrant provisioner — do not edit.
SQLNET.INBOUND_CONNECT_TIMEOUT = 400
EOF

log_section "Starting listener"
"${DB_HOME}/bin/lsnrctl" start
