#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# 07_setup_OracleNet.sh
#   Writes tnsnames.ora / listener.ora / sqlnet.ora on both nodes and
#   starts the local listener. Runs as the oracle user.
#------------------------------------------------------------------------------

# 中文说明：
# - 为主库和备库分别生成 Oracle Net 配置文件。
# - 根据当前主机角色写入本地监听地址并启动监听器。

. /vagrant/scripts/_common.sh

if [[ "$(id -un)" != "oracle" ]]; then
  log_error "该脚本必须以 oracle 用户运行"
  exit 1
fi

require_var DB_HOME
require_var DB_BASE
require_var DB_NAME
require_var NODE1_HOSTNAME
require_var NODE2_HOSTNAME

net_admin="${DB_HOME}/network/admin"
mkdir -p "${net_admin}"

# 中文：通过短主机名判断当前节点是主库还是备库。
current_host="$(hostname -s)"
case "${current_host}" in
  "${NODE1_HOSTNAME}") local_node="${NODE1_HOSTNAME}"; global_dbname="${DB_NAME}_DGMGRL" ;;
  "${NODE2_HOSTNAME}") local_node="${NODE2_HOSTNAME}"; global_dbname="${DB_NAME}_STDBY_DGMGRL" ;;
  *)
    log_error "主机名 '${current_host}' 既不是主库也不是备库"
    exit 1
    ;;
esac

log_section "在 ${current_host} 上写入 tnsnames.ora"
cat > "${net_admin}/tnsnames.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER = (ADDRESS = (PROTOCOL = TCP)(HOST = ${local_node})(PORT = 1521))

${DB_NAME} =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE1_HOSTNAME})(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${DB_NAME})
    )
  )

${DB_NAME}_STDBY =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE2_HOSTNAME})(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${DB_NAME})
    )
  )
EOF

log_section "在 ${current_host} 上写入 listener.ora"
cat > "${net_admin}/listener.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${local_node})(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = ${global_dbname})
      (ORACLE_HOME   = ${DB_HOME})
      (SID_NAME      = ${DB_NAME})
    )
  )

ADR_BASE_LISTENER = ${DB_BASE}
INBOUND_CONNECT_TIMEOUT_LISTENER = 400
EOF

log_section "写入 sqlnet.ora"
cat > "${net_admin}/sqlnet.ora" <<'EOF'
# Generated by Vagrant provisioner — do not edit.
SQLNET.INBOUND_CONNECT_TIMEOUT = 400
EOF

log_section "启动监听器"
"${DB_HOME}/bin/lsnrctl" start
