#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# setup.sh
#   Orchestrator for the Oracle Data Guard two-node provisioning flow.
#   Invoked by Vagrantfile on both primary and standby hosts.
#------------------------------------------------------------------------------

# 中文说明：
# - 该脚本是两节点 Oracle Data Guard 环境的总控入口。
# - 它会先生成共享环境文件，再按顺序完成系统、软件、数据库和收尾配置。


set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="/vagrant/scripts"

# Environment vars passed in by Vagrantfile (env: { ... }):
#   PROVIDER BOX_DISK_NUM VM1_NAME VM2_NAME SYSTEM_TIMEZONE PREFIX_NAME
#   DB_SOFTWARE DB_SOFTWARE_VER ORA_LANGUAGES DOMAIN
#   NODE1_PUBLIC_IP NODE2_PUBLIC_IP NODE1_PRIV_IP NODE2_PRIV_IP
#   ROOT_PASSWORD ORACLE_PASSWORD SYS_PASSWORD PDB_PASSWORD
#   DB_NAME PDB_NAME CDB ADG

for v in PROVIDER BOX_DISK_NUM VM1_NAME VM2_NAME SYSTEM_TIMEZONE \
         DB_SOFTWARE DB_VERSION DB_MAJOR DB_NAME \
         NODE1_PUBLIC_IP NODE2_PUBLIC_IP NODE1_PRIV_IP NODE2_PRIV_IP \
         ROOT_PASSWORD ORACLE_PASSWORD SYS_PASSWORD; do
  if [[ -z "${!v:-}" ]]; then
    echo "错误：缺少必需的环境变量 '${v}'" >&2
    exit 1
  fi
done

DB_HOME="/u01/app/oracle/product/${DB_VERSION}/dbhome_1"
SETUP_ENV_DIR="/etc/opt/oracle-dg"
SETUP_ENV_FILE="${SETUP_ENV_DIR}/setup.env"

write_env_export() {
  local name="$1"
  local value="${2-}"
  printf 'export %s=%q\n' "${name}" "${value}"
}

# Build the runtime setup.env file that is sourced by the other scripts.
# 中文：把敏感变量写入来宾机本地文件，供 root 和 oracle 脚本共享。
# Keep it on the guest filesystem rather than /vagrant so provider-specific
# synced-folder permissions do not block scripts that run as the oracle user.
install -d -m 0700 "${SETUP_ENV_DIR}"
( umask 077
  {
    printf '%s\n' \
      "# Generated by setup.sh. Do not edit by hand — will be overwritten on next 'vagrant up'." \
      '# Contains passwords.' \
      ''

    write_env_export PREFIX_NAME "${PREFIX_NAME}"
    printf '\n'

    write_env_export DB_SOFTWARE "${DB_SOFTWARE}"
    write_env_export DB_MAJOR "${DB_MAJOR}"
    write_env_export DB_VERSION "${DB_VERSION}"
    printf '\n'

    write_env_export SYS_PASSWORD "${SYS_PASSWORD}"
    write_env_export PDB_PASSWORD "${PDB_PASSWORD:-}"
    printf '\n'

    write_env_export NODE1_PUBLIC_IP "${NODE1_PUBLIC_IP}"
    write_env_export NODE2_PUBLIC_IP "${NODE2_PUBLIC_IP}"
    write_env_export NODE1_PRIV_IP "${NODE1_PRIV_IP}"
    write_env_export NODE2_PRIV_IP "${NODE2_PRIV_IP}"
    printf '\n'

    write_env_export DOMAIN_NAME "${DOMAIN}"
    write_env_export NODE1_HOSTNAME "${VM1_NAME}"
    write_env_export NODE2_HOSTNAME "${VM2_NAME}"
    printf '%s\n' \
      'export NODE1_FQ_HOSTNAME="${NODE1_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_HOSTNAME="${NODE2_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE1_PRIVNAME="${NODE1_HOSTNAME}-priv"' \
      'export NODE2_PRIVNAME="${NODE2_HOSTNAME}-priv"' \
      'export NODE1_FQ_PRIVNAME="${NODE1_PRIVNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_PRIVNAME="${NODE2_PRIVNAME}.${DOMAIN_NAME}"' \
      ''

    write_env_export ORA_LANGUAGES "${ORA_LANGUAGES}"
    write_env_export ORA_INVENTORY '/u01/app/oraInventory'
    write_env_export DB_BASE '/u01/app/oracle'
    write_env_export DB_HOME "${DB_HOME}"
    write_env_export DB_NAME "${DB_NAME}"
    write_env_export PDB_NAME "${PDB_NAME:-}"
    write_env_export CDB "${CDB}"
    write_env_export ADG "${ADG}"
    printf '\n'

    write_env_export INFO '\033[0;34mINFO: \033[0m'
    write_env_export ERROR '\033[1;31mERROR: \033[0m'
    write_env_export SUCCESS '\033[1;32mSUCCESS: \033[0m'
  } > "${SETUP_ENV_FILE}"
)
chmod 0600 "${SETUP_ENV_FILE}"

# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_common.sh"

log_section "修复 locale 警告"
for line in 'LANG=en_US.utf-8' 'LC_ALL=en_US.utf-8'; do
  grep -qxF "${line}" /etc/environment || echo "${line}" >> /etc/environment
done

log_section "将系统时区设置为 ${SYSTEM_TIMEZONE}"
timedatectl set-timezone "${SYSTEM_TIMEZONE}"

log_section "安装操作系统软件包"
bash "${SCRIPT_DIR}/01_install_os_packages.sh"

log_section "配置 /u01 磁盘"
bash "${SCRIPT_DIR}/02_setup_u01.sh" "${BOX_DISK_NUM}" "${PROVIDER}"

log_section "配置 oradata 磁盘（/u02）"
ORADATA_DISK_OFFSET=$((BOX_DISK_NUM + 1))
bash "${SCRIPT_DIR}/03_setup_oradata_disks.sh" "${ORADATA_DISK_OFFSET}" "${PROVIDER}"

log_section "配置 /etc/hosts 和 /etc/resolv.conf"
bash "${SCRIPT_DIR}/04_setup_hosts.sh"

log_section "配置操作系统用户和用户组"
bash "${SCRIPT_DIR}/05_setup_users.sh"

log_section "授予 oracle 访问运行时预配环境文件的权限"
chgrp oinstall "${SETUP_ENV_DIR}" "${SETUP_ENV_FILE}"
chmod 0750 "${SETUP_ENV_DIR}"
chmod 0640 "${SETUP_ENV_FILE}"

log_section "设置 root 和 oracle 账户密码"
# chpasswd reads from stdin — does not expose passwords via `ps`.
printf 'root:%s\n'   "${ROOT_PASSWORD}"   | chpasswd
printf 'oracle:%s\n' "${ORACLE_PASSWORD}" | chpasswd

log_section "安装 Oracle RDBMS 软件"
su - oracle -c "bash ${SCRIPT_DIR}/06_do_RDBMS_software_installation.sh"
bash "${ORA_INVENTORY}/orainstRoot.sh"
bash "${DB_HOME}/root.sh"

log_section "配置 Oracle Net（listener、tnsnames）"
su - oracle -c "bash ${SCRIPT_DIR}/07_setup_OracleNet.sh"

# 中文：根据当前主机名决定执行主库还是备库数据库配置。
current_host="$(hostname -s)"
if [[ "${current_host}" == "${NODE1_HOSTNAME}" ]]; then
  log_section "配置主库数据库"
  su - oracle -c "bash ${SCRIPT_DIR}/primary_DB_setup.sh"
elif [[ "${current_host}" == "${NODE2_HOSTNAME}" ]]; then
  log_section "配置备库数据库"
  su - oracle -c "bash ${SCRIPT_DIR}/standby_DB_setup.sh"
else
  log_error "主机名 '${current_host}' 既不匹配主库（${NODE1_HOSTNAME}）也不匹配备库（${NODE2_HOSTNAME}）"
  exit 1
fi

log_section "配置数据库自动启动"
bash "${SCRIPT_DIR}/08_setup_autostart.sh"

# Run user-defined post-setup scripts
# 中文：最后执行用户自定义脚本，方便在主流程后追加业务初始化。
log_section "运行用户自定义后置脚本（userscripts/）"
shopt -s nullglob
for f in /vagrant/userscripts/*; do
  case "${f,,}" in
    *.sh)
      log_info "正在执行 ${f}"
      # shellcheck disable=SC1090
      . "${f}"
      log_info "已完成 ${f}"
      ;;
    *.sql)
      log_info "正在以 SYS 身份执行 ${f}"
      su -l oracle -c "echo exit | sqlplus -s / as sysdba @\"${f}\""
      log_info "已完成 ${f}"
      ;;
    /vagrant/userscripts/put_custom_scripts_here.txt)
      : # skip placeholder
      ;;
    *)
      log_info "忽略 ${f}"
      ;;
  esac
done

log_success "预配完成"
