#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# setup.sh
#   Orchestrator for the Oracle RAC two-node provisioning flow.
#   Invoked by Vagrantfile on both nodes.
#------------------------------------------------------------------------------

# 中文说明：
# - 此脚本作为 RAC 总控入口，按顺序调用各阶段脚本并清理敏感环境变量。
# - 仅翻译面向使用者的提示信息，保留命令、变量、路径与配置键原样。

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="/vagrant/scripts"
: "${VAGRANT_PROVISION:=}"
echo "VAGRANT_PROVISION $VAGRANT_PROVISION"
# Env vars supplied by Vagrantfile — fail fast if any are missing.
for v in PROVIDER BOX_DISK_NUM SYSTEM_TIMEZONE PREFIX_NAME \
         VM1_NAME VM2_NAME DOMAIN \
         NODE1_PUBLIC_IP NODE1_PRIV_IP NODE1_VIP_IP \
         SCAN_IP1 SCAN_IP2 SCAN_IP3 \
         GI_SOFTWARE DB_SOFTWARE GI_VERSION DB_VERSION DB_MAJOR \
         ORA_LANGUAGES P1_RATIO ASM_DISK_NUM \
         NOMGMTDB ORESTART DB_NAME DB_TYPE CDB \
         ROOT_PASSWORD GRID_PASSWORD ORACLE_PASSWORD SYS_PASSWORD; do
  if [[ -z "${!v:-}" ]]; then
    echo "错误：缺少必需的环境变量 '${v}'" >&2
    exit 1
  fi
done

# host2 vars are only required in cluster mode.
if [[ "${ORESTART}" != "true" ]]; then
  for v in NODE2_PUBLIC_IP NODE2_PRIV_IP NODE2_VIP_IP; do
    if [[ -z "${!v:-}" ]]; then
      echo "错误：缺少必需的环境变量 '${v}'（集群模式）" >&2
      exit 1
    fi
  done
fi

# ---------------------------------------------------------------------
# Derived paths
# ---------------------------------------------------------------------
GRID_BASE="/u01/app/grid"
DB_BASE="/u01/app/oracle"
GI_HOME="/u01/app/${GI_VERSION%.*}/grid"          # 19.3.0.0 → 19.3.0
DB_HOME="/u01/app/oracle/product/${DB_VERSION%.*}/dbhome_1"
ORA_INVENTORY="/u01/app/oraInventory"
CLUSTER_NAME="${PREFIX_NAME}-c"
SCAN_NAME="${PREFIX_NAME}-scan"
SCAN_PORT=1521

# Public / private subnets (derived from node1's addresses).
IFS='.' read -r p1 p2 p3 _ <<< "${NODE1_PUBLIC_IP}"
PUBLIC_SUBNET="${p1}.${p2}.${p3}.0"
IFS='.' read -r p1 p2 p3 _ <<< "${NODE1_PRIV_IP}"
PRIVATE_SUBNET="${p1}.${p2}.${p3}.0"

SETUP_ENV_DIR="/etc/opt/oracle-rac"
SETUP_ENV_FILE="${SETUP_ENV_DIR}/setup.env"

write_env_export() {
  local name="$1" value="${2-}"
  printf 'export %s=%q\n' "${name}" "${value}"
}

# ---------------------------------------------------------------------
# 把运行期变量集中写入 setup.env，供 root、grid 和 oracle 共享。
# Build the runtime setup.env (sourced by every other script).
# Mode 0640, owned by root:oinstall (written before oinstall exists, so
# the final chown/chmod runs after 05_setup_users.sh).
# ---------------------------------------------------------------------
install -d -m 0700 "${SETUP_ENV_DIR}"
( umask 077
  {
    printf '%s\n' \
      "# Generated by setup.sh. Do not edit by hand — will be overwritten on next 'vagrant up'." \
      '# Contains passwords; mode 0640 root:oinstall after user setup.' \
      ''

    write_env_export PREFIX_NAME       "${PREFIX_NAME}"
    write_env_export DOMAIN_NAME       "${DOMAIN}"
    write_env_export CLUSTER_NAME      "${CLUSTER_NAME}"
    printf '\n'

    write_env_export GI_SOFTWARE       "${GI_SOFTWARE}"
    write_env_export DB_SOFTWARE       "${DB_SOFTWARE}"
    write_env_export GI_VERSION        "${GI_VERSION}"
    write_env_export DB_VERSION        "${DB_VERSION}"
    write_env_export DB_MAJOR          "${DB_MAJOR}"
    printf '\n'

    write_env_export ORA_INVENTORY     "${ORA_INVENTORY}"
    write_env_export GRID_BASE         "${GRID_BASE}"
    write_env_export DB_BASE           "${DB_BASE}"
    write_env_export GI_HOME           "${GI_HOME}"
    write_env_export DB_HOME           "${DB_HOME}"
    write_env_export ORA_LANGUAGES     "${ORA_LANGUAGES}"
    printf '\n'

    write_env_export P1_RATIO          "${P1_RATIO}"
    write_env_export ASM_DISK_NUM      "${ASM_DISK_NUM}"
    write_env_export NOMGMTDB          "${NOMGMTDB}"
    write_env_export ORESTART          "${ORESTART}"
    printf '\n'

    write_env_export NODE1_HOSTNAME    "${VM1_NAME}"
    write_env_export NODE2_HOSTNAME    "${VM2_NAME}"
    write_env_export NODE1_PUBLIC_IP   "${NODE1_PUBLIC_IP}"
    write_env_export NODE2_PUBLIC_IP   "${NODE2_PUBLIC_IP:-}"
    write_env_export NODE1_PRIV_IP     "${NODE1_PRIV_IP}"
    write_env_export NODE2_PRIV_IP     "${NODE2_PRIV_IP:-}"
    write_env_export NODE1_VIP_IP      "${NODE1_VIP_IP}"
    write_env_export NODE2_VIP_IP      "${NODE2_VIP_IP:-}"
    write_env_export SCAN_IP1          "${SCAN_IP1}"
    write_env_export SCAN_IP2          "${SCAN_IP2}"
    write_env_export SCAN_IP3          "${SCAN_IP3}"
    write_env_export PUBLIC_SUBNET     "${PUBLIC_SUBNET}"
    write_env_export PRIVATE_SUBNET    "${PRIVATE_SUBNET}"
    printf '\n'

    printf '%s\n' \
      'export NODE1_FQ_HOSTNAME="${NODE1_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_HOSTNAME="${NODE2_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE1_VIPNAME="${NODE1_HOSTNAME}-vip"' \
      'export NODE2_VIPNAME="${NODE2_HOSTNAME}-vip"' \
      'export NODE1_FQ_VIPNAME="${NODE1_VIPNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_VIPNAME="${NODE2_VIPNAME}.${DOMAIN_NAME}"' \
      'export NODE1_PRIVNAME="${NODE1_HOSTNAME}-priv"' \
      'export NODE2_PRIVNAME="${NODE2_HOSTNAME}-priv"' \
      'export NODE1_FQ_PRIVNAME="${NODE1_PRIVNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_PRIVNAME="${NODE2_PRIVNAME}.${DOMAIN_NAME}"' \
      ''
    write_env_export SCAN_NAME         "${SCAN_NAME}"
    printf '%s\n' 'export FQ_SCAN_NAME="${SCAN_NAME}.${DOMAIN_NAME}"'
    write_env_export SCAN_PORT         "${SCAN_PORT}"
    printf '\n'

    write_env_export DB_NAME           "${DB_NAME}"
    write_env_export PDB_NAME          "${PDB_NAME:-}"
    write_env_export DB_TYPE           "${DB_TYPE}"
    write_env_export CDB               "${CDB}"
    printf '\n'

    # Passwords — stored here so post-boot scripts can use them without
    # round-tripping through Vagrant env. File is mode 0640 root:oinstall.
    write_env_export SYS_PASSWORD      "${SYS_PASSWORD}"
    write_env_export PDB_PASSWORD      "${PDB_PASSWORD:-}"
    printf '\n'

    write_env_export INFO '\033[0;34m信息：\033[0m'
    write_env_export ERROR '\033[1;31m错误：\033[0m'
    write_env_export SUCCESS '\033[1;32m成功：\033[0m'
  } > "${SETUP_ENV_FILE}"
)
chmod 0600 "${SETUP_ENV_FILE}"

# Common helpers + ERR trap
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_common.sh"

# ---------------------------------------------------------------------
# Provider quirk: after base-box shell provisioning, VirtualBox sometimes
# loses the shared-folder mount; re-mount defensively.
# ---------------------------------------------------------------------
if [[ "${PROVIDER}" == "virtualbox" ]] && ! mountpoint -q /vagrant; then
  log_info "正在重新挂载 /vagrant（vboxsf）"
  mount -t vboxsf vagrant /vagrant
fi

log_section "正在修复 locale 警告"
for line in 'LANG=zh_CN.utf-8' 'LC_ALL=zh_CN.utf-8'; do
  grep -qxF "${line}" /etc/environment || echo "${line}" >> /etc/environment
done

log_section "正在将系统时区设置为 ${SYSTEM_TIMEZONE}"
timedatectl set-timezone "${SYSTEM_TIMEZONE}"

# Oracle's root SSH equivalence bootstrap is password-based; keep it enabled
# until node1 has finished creating root keys for the cluster.
log_section "正在为引导阶段准备 sshd"
bash "${SCRIPT_DIR}/00_configure_root_ssh.sh" yes

log_section "正在安装操作系统软件包"
bash "${SCRIPT_DIR}/01_install_os_packages.sh"

log_section "正在配置 /u01 磁盘"
bash "${SCRIPT_DIR}/02_setup_u01.sh" "${BOX_DISK_NUM}" "${PROVIDER}"

log_section "正在配置 /etc/hosts 和 /etc/resolv.conf"
bash "${SCRIPT_DIR}/03_setup_hosts.sh"

log_section "正在配置 chronyd"
bash "${SCRIPT_DIR}/04_setup_chrony.sh"

log_section "正在配置操作系统用户和用户组"
bash "${SCRIPT_DIR}/05_setup_users.sh"

log_section "正在为 oinstall 组授予运行期预配环境访问权限"
chgrp oinstall "${SETUP_ENV_DIR}" "${SETUP_ENV_FILE}"
chmod 0750     "${SETUP_ENV_DIR}"
chmod 0640     "${SETUP_ENV_FILE}"

log_section "正在设置 root、grid 和 oracle 账户口令"
# chpasswd reads from stdin — passwords never hit `ps`.
printf 'root:%s\n'   "${ROOT_PASSWORD}"   | chpasswd
printf 'grid:%s\n'   "${GRID_PASSWORD}"   | chpasswd
printf 'oracle:%s\n' "${ORACLE_PASSWORD}" | chpasswd

log_section "正在配置共享 ASM 磁盘"
SHARED_DISK_OFFSET=$((BOX_DISK_NUM + 1))
bash "${SCRIPT_DIR}/06_setup_shared_disks.sh" "${SHARED_DISK_OFFSET}" "${PROVIDER}"

current_host="$(hostname -s)"
is_node1="false"
[[ "${current_host}" == "${VM1_NAME}" ]] && is_node1="true"

# -------------------- node1 only (cluster) OR node1 (orestart) -------
if [[ "${VAGRANT_PROVISION}" != "true" && "${is_node1}" == "true" && "${ORESTART}" == "false" ]] \
   || [[ "${ORESTART}" == "true" ]]; then

  log_section "正在准备 Grid Infrastructure 安装介质"
  bash "${SCRIPT_DIR}/07_extract_gi.sh"

  if [[ "${ORESTART}" == "false" ]]; then
    log_section "正在为 grid 和 oracle 配置 SSH 互信"
    bash "${SCRIPT_DIR}/08_setup_user_equ.sh" grid   "${GRID_PASSWORD}"   "${VM1_NAME}" "${VM2_NAME}"
    bash "${SCRIPT_DIR}/08_setup_user_equ.sh" oracle "${ORACLE_PASSWORD}" "${VM1_NAME}" "${VM2_NAME}"
  fi

  log_section "正在安装 cvuqdisk"
  yum install -y "${GI_HOME}"/cv/rpm/cvuqdisk*.rpm

  log_section "正在安装 Grid Infrastructure（静默模式，含软件和配置）"
  su - grid -c "bash ${SCRIPT_DIR}/10_gi_installation.sh"

  if [[ "${ORESTART}" == "false" ]]; then
    log_section "正在为 root 配置 SSH 互信（root.sh 所需）"
    bash "${SCRIPT_DIR}/08_setup_user_equ.sh" root "${ROOT_PASSWORD}" "${VM1_NAME}" "${VM2_NAME}"
  fi

  log_section "正在运行 GI root 脚本"
  bash "${SCRIPT_DIR}/11_gi_root.sh"

  log_section "正在执行 GI 配置工具"
  su - grid -c "bash ${SCRIPT_DIR}/12_gi_config.sh"

  log_section "正在创建 RECO 磁盘组"
  su - grid -c "bash ${SCRIPT_DIR}/13_make_reco_dg.sh"

  log_section "正在准备 RDBMS 安装介质"
  bash "${SCRIPT_DIR}/14_extract_db.sh"
  log_section "正在安装 RDBMS 软件"
  su - oracle -c "bash ${SCRIPT_DIR}/15_db_software_installation.sh"
  bash "${DB_HOME}/root.sh"
  if [[ "${ORESTART}" == "false" ]]; then
    ssh -o StrictHostKeyChecking=no "root@${VM2_NAME}" "bash ${DB_HOME}/root.sh"
  fi

  log_section "正在创建数据库 ${DB_NAME}"
  su - oracle -c "bash ${SCRIPT_DIR}/16_create_database.sh"

  log_section "正在检查数据库"
  su - oracle -c "bash ${SCRIPT_DIR}/17_check_database.sh"
fi

# Run user-defined post-setup scripts on every node.
# 所有系统级配置结束后，再执行用户自定义脚本。
log_section "正在运行用户自定义的后置脚本 (userscripts/)"
shopt -s nullglob
for f in /vagrant/userscripts/*; do
  case "${f,,}" in
    *.sh)
      log_info "running ${f}"
      # shellcheck disable=SC1090
      . "${f}"
      log_info "done ${f}"
      ;;
    *.sql)
      log_info "正在以 SYS 身份运行 ${f}"
      su -l oracle -c "echo exit | sqlplus -s / as sysdba @\"${f}\""
      log_info "done ${f}"
      ;;
    /vagrant/userscripts/put_custom_scripts_here.txt)
      :
      ;;
    *)
      log_info "ignoring ${f}"
      ;;
  esac
done

if [[ "${ORESTART}" == "true" ]]; then
  log_section "正在在 ${current_host} 上将 root SSH 重新锁定为仅密钥登录"
  bash "${SCRIPT_DIR}/00_configure_root_ssh.sh" prohibit-password
elif [[ "${VAGRANT_PROVISION}" != "true" && "${is_node1}" == "true" ]]; then
  log_section "正在在整个集群中将 root SSH 重新锁定为仅密钥登录"
  ssh -o StrictHostKeyChecking=no "root@${VM2_NAME}" \
    "bash ${SCRIPT_DIR}/00_configure_root_ssh.sh prohibit-password"
  bash "${SCRIPT_DIR}/00_configure_root_ssh.sh" prohibit-password
fi

# Strip DB passwords from the persistent setup.env now that bootstrap is done.
# Keeping them on disk would leave cleartext SYS/PDB credentials readable by
# any member of oinstall (grid, oracle) for the life of the VM.
log_section "正在从 ${SETUP_ENV_FILE} 清除数据库口令"
if [[ -f "${SETUP_ENV_FILE}" ]]; then
  sed -ri '/^export (SYS_PASSWORD|PDB_PASSWORD)=/d' "${SETUP_ENV_FILE}"
fi

log_success "${current_host} 上的预配已完成"
